steps:
  # Step 1: Deploy FastAPI to f1-dev
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=f1-dev'
    args:
      - 'apply'
      - '-f'
      - './kubernetes/fastapi.yaml'
    id: 'Deploy FastAPI to f1-dev'

  # Step 2: Deploy Streamlit to f1-dev
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=f1-dev'
    args:
      - 'apply'
      - '-f'
      - './kubernetes/streamlit.yaml'
    id: 'Deploy Streamlit to f1-dev'

  # Step 3: Deploy FastAPI to f1-production
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=f1-production'
    args:
      - 'apply'
      - '-f'
      - './kubernetes/fastapi.yaml'
    id: 'Deploy FastAPI to f1-production'

  # Step 4: Deploy Streamlit to f1-production
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=f1-production'
    args:
      - 'apply'
      - '-f'
      - './kubernetes/streamlit.yaml'
    id: 'Deploy Streamlit to f1-production'

timeout: '600s'