apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: "Development environment for GKE applications"
gke:
  cluster: projects/my-project/locations/us-central1/clusters/f1-dev