apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
  annotations: {}
  labels: {}
description: "Production Environment"
gke:
  cluster: projects/my-project/locations/us-central1/clusters/f1-prod